version: '3'
services:
  webapp:
    image: node:stretch
    env_file: .env
    volumes:
      - .:/opt/app
    working_dir: /opt/app
  awscli:
    image: amazon/aws-cli
    env_file: .env
    volumes:
      - ./build:/opt/app
      - ~/.aws:/root/.aws
    working_dir: /opt/app